#!/usr/bin/env bash
# A script to install Nginx web server

# Install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Start nginx
sudo service nginx start

# Create a new HTML file
echo "Hello World!" > /var/www/html/index.html

# Reload Nginx configuration
nginx -s reload
