#!/usr/bin/env bash
# Installing nginx web server
sudo apt-get  update -y
sudo apt-get install nginx -y

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" > /var/www/html/index.html

# Starting nginx
sudo service nginx start
