#!/usr/bin/env bash
# A script to install Nginx web server

# Install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Create a new HTML file
echo "Hello World!" |sudo tee /var/www/html/index.html

# Start nginx
sudo service nginx start
