#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get update -y
sudo apt-get install -y nginx

sed -i "48i\\\tif (\$request_filename ~ redirect_me){\n\t\t\
rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites-available/default

service nginx restart
