#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get update -y
sudo apt-get install -y nginx
echo "server {
	listen 80;
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/new_page;
	}

	location / {
		return 200 "Hello World!";
	}
}" > /etc/nginx/sites-available/redirect

ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
rm /etc/nginx/sites-enabled/default

service nginx restart
