#!/usr/bin/env bash

# Install HAproxy if not already installed
if ! command -v haproxy &> /dev/null; then
	sudo apt update
	sudo apt install -y haproxy
fi

# Configure HAproxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
frontend web_servers
	bind *:80
	mode http
	default_backend backend_servers

backend backend_servers
	mode http
	balance roundrobin
	server web_01 172654-web-01:80 check
	server web-02 172654-web-02:80 check
EOF'

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1' /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
