#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

#pgrep gunicorn | awk '{ print $2 }' | xargs kill -HUP

pkill -HUP gunicorn

/home/vagrant/AirBnB_clone_v4/bin/gunicorn --bind 0.0.0.0:8001 --workers 4 web_flask.0-hello_route:app
